name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test
    
    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Configure NuGet credentials
      run: |
        echo "Setting up NuGet credentials..."
        echo "machine nuget.pkg.github.com" > ~/.netrc
        echo "login LucasBLs" >> ~/.netrc
        echo "password ${{ secrets.GITHUB_PACKAGES_TOKEN }}" >> ~/.netrc

    - name: Publish
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.GITHUB_PACKAGES_TOKEN }} -s https://nuget.pkg.github.com/LucasBLs/index.json
